@extends('layouts.app')

@section('title', 'Payslip Detail')

@section('content')
<div class="page-header">
    <div>
        <h2 class="page-h2">Payslip — {{ $payslip->month }} {{ $payslip->year }}</h2>
        <p class="page-sub">{{ $payslip->employee->full_name }} ({{ $payslip->employee->employee_no }})</p>
    </div>
    <div style="display:flex;gap:10px">
        <button onclick="window.print()" class="btn">
            <i class="ti ti-printer"></i> Print
        </button>
        <a href="{{ route('payslips.index') }}" class="btn">
            <i class="ti ti-arrow-left"></i> Back
        </a>
    </div>
</div>

<div class="card" id="payslip-print" style="max-width:700px;margin:0 auto">
    <div style="text-align:center;padding-bottom:1.5rem;border-bottom:2px solid var(--accent);margin-bottom:1.5rem">
        <div style="font-size:20px;font-weight:700;color:var(--accent)">StaffHub Sdn Bhd</div>
        <div style="font-size:13px;color:var(--text2);margin-top:4px">Payslip for {{ $payslip->month }} {{ $payslip->year }}</div>
    </div>

    <div class="form-row" style="margin-bottom:1.5rem">
        <div>
            <div style="font-size:12px;color:var(--text3);margin-bottom:4px">Employee Name</div>
            <div style="font-weight:600">{{ $payslip->employee->full_name }}</div>
        </div>
        <div>
            <div style="font-size:12px;color:var(--text3);margin-bottom:4px">Employee No</div>
            <div style="font-weight:600">{{ $payslip->employee->employee_no }}</div>
        </div>
    </div>

    <div class="form-row" style="margin-bottom:1.5rem">
        <div>
            <div style="font-size:12px;color:var(--text3);margin-bottom:4px">Department</div>
            <div style="font-weight:600">{{ $payslip->employee->department->name ?? '-' }}</div>
        </div>
        <div>
            <div style="font-size:12px;color:var(--text3);margin-bottom:4px">Position</div>
            <div style="font-weight:600">{{ $payslip->employee->position }}</div>
        </div>
    </div>

    <table style="margin-bottom:1rem">
        <thead>
            <tr>
                <th>Earnings</th>
                <th style="text-align:right">Amount (RM)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Basic Salary</td>
                <td style="text-align:right">{{ number_format($payslip->basic_salary, 2) }}</td>
            </tr>
            <tr>
                <td>Allowance</td>
                <td style="text-align:right">{{ number_format($payslip->allowance, 2) }}</td>
            </tr>
            <tr>
                <td>Overtime</td>
                <td style="text-align:right">{{ number_format($payslip->overtime, 2) }}</td>
            </tr>
            <tr style="font-weight:700;background:#fafafa">
                <td>Gross Salary</td>
                <td style="text-align:right">{{ number_format($payslip->gross_salary, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <table style="margin-bottom:1rem">
        <thead>
            <tr>
                <th>Deductions</th>
                <th style="text-align:right">Amount (RM)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>EPF</td>
                <td style="text-align:right">{{ number_format($payslip->epf_deduction, 2) }}</td>
            </tr>
            <tr>
                <td>SOCSO</td>
                <td style="text-align:right">{{ number_format($payslip->socso_deduction, 2) }}</td>
            </tr>
            <tr>
                <td>PCB / Income Tax</td>
                <td style="text-align:right">{{ number_format($payslip->pcb_deduction, 2) }}</td>
            </tr>
            <tr>
                <td>Other Deduction</td>
                <td style="text-align:right">{{ number_format($payslip->other_deduction, 2) }}</td>
            </tr>
            <tr style="font-weight:700;background:#fafafa">
                <td>Total Deduction</td>
                <td style="text-align:right">{{ number_format($payslip->total_deduction, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div style="background:var(--accent-light);padding:1.25rem;border-radius:var(--radius);display:flex;justify-content:space-between;align-items:center">
        <div style="font-size:16px;font-weight:700;color:var(--accent)">NET SALARY</div>
        <div style="font-size:24px;font-weight:800;color:var(--accent)">RM {{ number_format($payslip->net_salary, 2) }}</div>
    </div>

    <div style="text-align:center;margin-top:1.5rem;font-size:11px;color:var(--text3)">
        Generated by {{ $payslip->generatedBy->name ?? 'System' }} on {{ $payslip->created_at->format('d M Y, h:i A') }}
        <br>This is a computer-generated payslip and does not require a signature.
    </div>
</div>

<style>
@media print {
    .sidebar, .topbar, .page-header { display:none !important; }
    .main { margin-left:0 !important; }
    body { background:#fff !important; }
}
</style>
@endsection